In [1]:
import torch
import numpy as np

torch.__version__

'2.2.0.post100'

In [2]:
arr = np.array([1,2,3,4])

In [16]:
tx = torch.from_numpy(arr)
ctx = torch.tensor(arr)
type(tx)
tx.dtype

torch.int64

In [17]:
arr2d = np.arange(0, 12)
arr2d = arr2d.reshape(4,3)
tx2 = torch.from_numpy(arr2d)

In [18]:
tx2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [24]:
arr[0] = 69
arr
tx
ctx

tensor([1, 2, 3, 4])

In [51]:
torch.zeros(4,3, dtype=torch.int32)
torch.ones(4,3)
torch.arange(0, 18, 2).reshape(3,3)
ten = torch.linspace(1, 18, 12).reshape(3,4)
int_ten = ten.type(torch.int32)

In [52]:
torch.rand(4,3)
torch.randn(4,3) # standard normal distribution
torch.randint(0, 11, size=(5,5))

tensor([[ 2,  6,  6,  6,  9],
        [ 3,  8,  9,  1,  4],
        [ 2,  6,  0,  7,  7],
        [10,  0,  2,  9,  7],
        [ 1,  6,  0, 10, 10]])

In [53]:
torch.rand_like(ten)

tensor([[0.0583, 0.9840, 0.0103, 0.8143],
        [0.3207, 0.2921, 0.7045, 0.7730],
        [0.8111, 0.2923, 0.3132, 0.0731]])

In [64]:
torch.numel(ten)
torch.norm(ten)
torch.dot(ten[:,1], ten[:,0])
torch.mm(ten, ten.reshape(4,3))

tensor([[141.4050, 161.9174, 182.4297],
        [338.0992, 396.8265, 455.5537],
        [534.7934, 631.7356, 728.6777]])